services:
  - type: web
    name: soma
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SUPABASE_URL
        value: postgresql://postgres.dejojumyyydrlqoegqnf:IAFN4oKy9GAO1vN6@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: BREVO_API_KEY
        sync: false
      - key: DASHBOARD_USER
        sync: false
      - key: DASHBOARD_PASS
        sync: false
      - key: RENDER
        value: "true"



