services:
  - type: web
    name: soma
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SUPABASE_URL
        value: postgresql://postgres.dejojumyyydrlqoegqnf:IAFN4oKy9GAO1vN6@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SENDGRID_API_KEY
        sync: false

      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_USE_SSL
        value: "true"
      - key: RENDER
        value: "true"



